### ISSUE TITLE
Mise à jour de keneodev

### ISSUE THREAD

**Issue by arimorc** [paulld/keneo#22]
Histoire de pouvoir faire tester le client

**Comment by paulld** [comment]
Voilà c'est fait, mais le serveur saute souvent aujourd'hui, sur dev comme sur test. As-tu rencontré cela de ton côté ? 
![screen shot 2015-01-05 at 22 44 57](https://cloud.githubusercontent.com/assets/7286592/5614495/d2e0b904-952c-11e4-9e0d-3cd1badeb714.png)

**Comment by arimorc** [comment]
Keneo m’a dit la même chose et je l’ai constaté aussi.
J’espère qu’aujourd’hui, ce sera mieux.

Cheers,

Romaric.

De : Paul [mailto:notifications@github.com]
Envoyé : lundi 5 janvier 2015 15:49
À : paulld/keneo
Cc : Barthe, R. [Arimor C.]
Objet : Re: [keneo] Mise à jour de keneodev (#22)


Voilà c'est fait, mais le serveur saute souvent aujourd'hui, sur dev comme sur test. As-tu rencontré cela de ton côté ?
[screen shot 2015-01-05 at 22 44 57]<https://cloud.githubusercontent.com/assets/7286592/5614495/d2e0b904-952c-11e4-9e0d-3cd1badeb714.png>

**Comment by paulld** [comment]
Ça a l'air d'aller mieux non?
Tout est en ligne maintenant, y compris mes dernières modifs d'aujourd'hui ainsi que les tiennes.

**Comment by arimorc** [comment]
Ca à l’air oui. Keneo confirme aussi.
Comment va ?

De : Paul [mailto:notifications@github.com]
Envoyé : mardi 6 janvier 2015 15:56
À : paulld/keneo
Cc : Barthe, R. [Arimor C.]
Objet : Re: [keneo] Mise à jour de keneodev (#22)


Ça a l'air d'aller mieux non?
Tout est en ligne maintenant, y compris mes dernières modifs d'aujourd'hui ainsi que les tiennes.
